package com.solidextend.sys.prompt.vo;

public class PromptMsg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PROMPT_MSG.ID
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PROMPT_MSG.CODE
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PROMPT_MSG.CONTENT
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    private Object content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PROMPT_MSG.REF_CODE
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    private String refCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PROMPT_MSG.IS_PUBLIC
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    private String isPublic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PROMPT_MSG.ID
     *
     * @return the value of SYS_PROMPT_MSG.ID
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PROMPT_MSG.ID
     *
     * @param id the value for SYS_PROMPT_MSG.ID
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PROMPT_MSG.CODE
     *
     * @return the value of SYS_PROMPT_MSG.CODE
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PROMPT_MSG.CODE
     *
     * @param code the value for SYS_PROMPT_MSG.CODE
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PROMPT_MSG.CONTENT
     *
     * @return the value of SYS_PROMPT_MSG.CONTENT
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    public Object getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PROMPT_MSG.CONTENT
     *
     * @param content the value for SYS_PROMPT_MSG.CONTENT
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    public void setContent(Object content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PROMPT_MSG.REF_CODE
     *
     * @return the value of SYS_PROMPT_MSG.REF_CODE
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    public String getRefCode() {
        return refCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PROMPT_MSG.REF_CODE
     *
     * @param refCode the value for SYS_PROMPT_MSG.REF_CODE
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    public void setRefCode(String refCode) {
        this.refCode = refCode == null ? null : refCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PROMPT_MSG.IS_PUBLIC
     *
     * @return the value of SYS_PROMPT_MSG.IS_PUBLIC
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    public String getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PROMPT_MSG.IS_PUBLIC
     *
     * @param isPublic the value for SYS_PROMPT_MSG.IS_PUBLIC
     *
     * @mbggenerated Thu Dec 19 14:24:23 CST 2013
     */
    public void setIsPublic(String isPublic) {
        this.isPublic = isPublic == null ? null : isPublic.trim();
    }
}