package com.solidextend.sys.role.vo;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ID
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    private Object roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.REMARK
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    private Object remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_TYPE
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    private String roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ORGAN_ID
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    private String organId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ID
     *
     * @return the value of SYS_ROLE.ID
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ID
     *
     * @param id the value for SYS_ROLE.ID
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_NAME
     *
     * @return the value of SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    public Object getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_NAME
     *
     * @param roleName the value for SYS_ROLE.ROLE_NAME
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    public void setRoleName(Object roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.REMARK
     *
     * @return the value of SYS_ROLE.REMARK
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    public Object getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.REMARK
     *
     * @param remark the value for SYS_ROLE.REMARK
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    public void setRemark(Object remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_TYPE
     *
     * @return the value of SYS_ROLE.ROLE_TYPE
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_TYPE
     *
     * @param roleType the value for SYS_ROLE.ROLE_TYPE
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ORGAN_ID
     *
     * @return the value of SYS_ROLE.ORGAN_ID
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    public String getOrganId() {
        return organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ORGAN_ID
     *
     * @param organId the value for SYS_ROLE.ORGAN_ID
     *
     * @mbggenerated Fri Jan 03 13:34:10 CST 2014
     */
    public void setOrganId(String organId) {
        this.organId = organId == null ? null : organId.trim();
    }
}