package com.solidextend.sys.sms.vo;

public class SmsReceiver {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SMS_RECEIVER.ID
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SMS_RECEIVER.SMS_CONTENT_ID
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    private String smsContentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SMS_RECEIVER.MOBILE_NO
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    private String mobileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SMS_RECEIVER.RECEIVER_ID
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    private String receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SMS_RECEIVER.RECEIVER_NAME
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SMS_RECEIVER.SEND_TIME
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    private String sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SMS_RECEIVER.STATE
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SMS_RECEIVER.ID
     *
     * @return the value of SYS_SMS_RECEIVER.ID
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SMS_RECEIVER.ID
     *
     * @param id the value for SYS_SMS_RECEIVER.ID
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SMS_RECEIVER.SMS_CONTENT_ID
     *
     * @return the value of SYS_SMS_RECEIVER.SMS_CONTENT_ID
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public String getSmsContentId() {
        return smsContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SMS_RECEIVER.SMS_CONTENT_ID
     *
     * @param smsContentId the value for SYS_SMS_RECEIVER.SMS_CONTENT_ID
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public void setSmsContentId(String smsContentId) {
        this.smsContentId = smsContentId == null ? null : smsContentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SMS_RECEIVER.MOBILE_NO
     *
     * @return the value of SYS_SMS_RECEIVER.MOBILE_NO
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SMS_RECEIVER.MOBILE_NO
     *
     * @param mobileNo the value for SYS_SMS_RECEIVER.MOBILE_NO
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SMS_RECEIVER.RECEIVER_ID
     *
     * @return the value of SYS_SMS_RECEIVER.RECEIVER_ID
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SMS_RECEIVER.RECEIVER_ID
     *
     * @param receiverId the value for SYS_SMS_RECEIVER.RECEIVER_ID
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId == null ? null : receiverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SMS_RECEIVER.RECEIVER_NAME
     *
     * @return the value of SYS_SMS_RECEIVER.RECEIVER_NAME
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SMS_RECEIVER.RECEIVER_NAME
     *
     * @param receiverName the value for SYS_SMS_RECEIVER.RECEIVER_NAME
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SMS_RECEIVER.SEND_TIME
     *
     * @return the value of SYS_SMS_RECEIVER.SEND_TIME
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SMS_RECEIVER.SEND_TIME
     *
     * @param sendTime the value for SYS_SMS_RECEIVER.SEND_TIME
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime == null ? null : sendTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SMS_RECEIVER.STATE
     *
     * @return the value of SYS_SMS_RECEIVER.STATE
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SMS_RECEIVER.STATE
     *
     * @param state the value for SYS_SMS_RECEIVER.STATE
     *
     * @mbggenerated Tue Feb 11 11:03:00 CST 2014
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}