package com.solidextend.sys.dict.vo;

public class Dict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICT.ID
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICT.DICT_CODE
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICT.DICT_NAME
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    private Object dictName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICT.REMARK
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    private Object remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICT.PARENT_ID
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICT.ORDER_NO
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    private Short orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICT.DICT_TYPE
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    private String dictType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICT.DELETED
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICT.ID
     *
     * @return the value of SYS_DICT.ID
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICT.ID
     *
     * @param id the value for SYS_DICT.ID
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICT.DICT_CODE
     *
     * @return the value of SYS_DICT.DICT_CODE
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICT.DICT_CODE
     *
     * @param dictCode the value for SYS_DICT.DICT_CODE
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICT.DICT_NAME
     *
     * @return the value of SYS_DICT.DICT_NAME
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public Object getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICT.DICT_NAME
     *
     * @param dictName the value for SYS_DICT.DICT_NAME
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public void setDictName(Object dictName) {
        this.dictName = dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICT.REMARK
     *
     * @return the value of SYS_DICT.REMARK
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public Object getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICT.REMARK
     *
     * @param remark the value for SYS_DICT.REMARK
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public void setRemark(Object remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICT.PARENT_ID
     *
     * @return the value of SYS_DICT.PARENT_ID
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICT.PARENT_ID
     *
     * @param parentId the value for SYS_DICT.PARENT_ID
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICT.ORDER_NO
     *
     * @return the value of SYS_DICT.ORDER_NO
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public Short getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICT.ORDER_NO
     *
     * @param orderNo the value for SYS_DICT.ORDER_NO
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public void setOrderNo(Short orderNo) {
        this.orderNo = orderNo;
    }

   
    /**
     * 字典类型 1具体字典 2字典类别
     * @return
     */
    public String getDictType() {
        return dictType;
    }

    
    /**
     * 字典类型 1具体字典 2字典类别
     * @param dictType
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICT.DELETED
     *
     * @return the value of SYS_DICT.DELETED
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICT.DELETED
     *
     * @param deleted the value for SYS_DICT.DELETED
     *
     * @mbggenerated Tue Dec 31 13:35:57 CST 2013
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
}